# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- philip-test

pool:
  vmImage: ubuntu-latest

jobs:
- job: audit_script
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - script: |
      npm audit
    displayName: 'npm audit'
    continueOnError: true
- job: audit_task
  steps:
  - task: Npm@1
    displayName: 'npm audit'
    inputs:
      command: custom
      customCommand: 'audit --registry=https://registry.npmjs.org/'
    continueOnError: true
