# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- philip-test

pool:
  vmImage: ubuntu-latest

stages:

- stage: audit
  jobs:
  - job: audit_script
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'
    - script: |
        npm audit
      displayName: 'npm audit'
      continueOnError: true

- stage: test
  jobs:
  - job: run_unit_tests
    variables:
      CI: true
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'
    - script: |
        npm ci
        npm test
      displayName: 'npm test'
